### ISSUE TITLE
QUESTION - Method of indexing erc721Transfers

### ISSUE THREAD

**Issue by Irfan-S** [spinamp/spindexer#44]
Spindexer seems to be indexing erc721Transfers via the contract address of the contract creators (Zora, Sound etc.). This seems to track sales of initial mints/sales, and/or transfers which have these contract addresses in them (An example would be Zora Auction house, which would be the intermediating contract between sales).

This won't track transfers between two users, say on OpenSea, where one user transfers their NFT via OpenSea's Seaport. 

Wanted to know if there was any active work being done to extract transfer information like this, which would make a better index of NFT activity in the music space involving trades and secondary sales.

On a side note the discord link on the README seems to have expired as well.

**Comment by musnit** [comment]
I'm not sure this is correct - we track transfers on the actual ERC721 token Contracts for the NFTs themselves, so transfers should be tracked irrespective of how they happen - a transfer of an ERC721 is expected to always emit an event on that token's contract.

(And to clarify, this is specifically for just the transfer of an NFT, not sales. If a transfer is part of a sale, that's a separate thing and is usually not tracked on the token contract and would rather be coming from the auction house. We do still need to add support for sales)
