### ISSUE TITLE
Add table for collectors/owners

### ISSUE THREAD

**Issue by puffo** [spinamp/spindexer#92]
- [x] build migrations
- [x] investigate Postgraphile ability to support backward compatibility
- [ ] build processor for transfers/mints

---

Loose spec:

 - take collectors out of nft field and make them a separate table with a JOIN table for a many:many relation between collectors and owners
 - put quantity on the join table with a default to 1 in the processor when the join record is created
 - handling transfers will need to update the quantity too (eg: when someone receives or sends an nft)
 - transfers/mints to a new collector that we don't know about will require creating that new collector in our collectors table and the new join
 - id field should be collector address
 - frontend will possibly need to be updated for nft queries on the collector page. alternatively, maybe we can ensure the API stays compatible

**Comment by puffo** [comment]
We'll need to initially ensure backward compatibility with the existing GQL queries, specifically:

```gql
query MyQuery {
  allNfts(
    filter: {owner: {equalToInsensitive: "0x96Acf191C0112806f9709366BaD77642B99B21a9"}}
    orderBy: CREATED_AT_TIME_DESC
  ) {
    edges {
      node {
        id
        nftsProcessedTracksByNftId {
          edges {
            node {
              processedTrackByProcessedTrackId {
                id
              }
            }
          }
        }
      }
    }
  }
}
```

We can try maintain this to start with and then follow up with a more robust deprecation path.

**Comment by puffo** [comment]
An update from some experiments with Postgraphile. Our options:

1. computed columns [(link)](https://www.graphile.org/postgraphile/computed-columns/)
2. advanced filtering [(link)](https://www.graphile.org/postgraphile/filtering/)

Attempting strategy 1. - tried to define a computed columns as follows:
```
  // generate Postgraphile computed-column for nfts owner
  await knex.raw(`
    CREATE FUNCTION ${Table.nfts}_owner(nft raw_nfts) RETURNS varchar AS $$
    SELECT ${Table.collectors}.id
    FROM ${Table.collectors}
    INNER JOIN ${Table.nftsCollectors} ON ${Table.nftsCollectors}."nftId" = nft.id
    $$ LANGUAGE sql STABLE;
  `);

  await knex.raw(`GRANT EXECUTE ON FUNCTION public.raw_nfts_owner(raw_nfts) TO ${process.env.POSTGRES_USERNAME_OPEN}`);

```

But it didn't look like it was hooking in correctly to give us the filtering functionality, giving this GQL error:
```Field \"owner\" is not defined by type \"NftFilter\"```

Seeing as we're not using live queries, I'll try experiment with the suggestions listed for strategy 2.

**Comment by musnit** [comment]
> An update from some experiments with Postgraphile. Our options:
> 
> 1. computed columns [(link)](https://www.graphile.org/postgraphile/computed-columns/)
> 2. advanced filtering [(link)](https://www.graphile.org/postgraphile/filtering/)
> 
> Attempting strategy 1. - tried to define a computed columns as follows:
> 
> ```
>   // generate Postgraphile computed-column for nfts owner
>   await knex.raw(`
>     CREATE FUNCTION ${Table.nfts}_owner(nft raw_nfts) RETURNS varchar AS $$
>     SELECT ${Table.collectors}.id
>     FROM ${Table.collectors}
>     INNER JOIN ${Table.nftsCollectors} ON ${Table.nftsCollectors}."nftId" = nft.id
>     $$ LANGUAGE sql STABLE;
>   `);
> 
>   await knex.raw(`GRANT EXECUTE ON FUNCTION public.raw_nfts_owner(raw_nfts) TO ${process.env.POSTGRES_USERNAME_OPEN}`);
> ```
> 
> But it didn't look like it was hooking in correctly to give us the filtering functionality, giving this GQL error: `Field \"owner\" is not defined by type \"NftFilter\"`
> 
> Seeing as we're not using live queries, I'll try experiment with the suggestions listed for strategy 2.

hmm yeah we haven't really tried computed columns yet, but did it work for the actual nft query even though it didn't for the filter?

also, if someone is querying for like 20 records would this result in that function being queried 20 times, once for each nft, rather than one time with a batch select? may be bad for performance if so
