### ISSUE TITLE
Allow new platforms/contracts/etc without any migrations

### ISSUE THREAD

**Issue by Geimaj** [spinamp/spindexer#97]
Considerations
 - All platforms are seeded purely via manual/hardcoded inserts
 - All metafactories are seeded purely via manual/hardcoded inserts
 - Some nftfactories are seeded via manual/hardcoded inserts, some come from metafactories

We could extract all the manual inserts into a set of seed files, with a script that generates seed file backup from live db and periodically and commits to repo periodically. Then we could add an API to insert stuff dynamically.

Core challenge is to distinguish btwn seeded nftfactories and generated ones, because we won't want generated ones in the seed file. Maybe can just add a relation and query for null relations?

**Comment by Geimaj** [comment]
Partially solved by #64 as we now have the ability to create seeds and ingest that data into the DB. 

Maybe just need to extract all the current migrations into seeds, and insert new records via an api that updates the seeds table. We can then periodically back up the seeds table, and I don't think we would need an extra relation to distinguish between generated records and seeded ones, because only seeded records will exist in the seeds table

**Comment by musnit** [comment]
> 

yep sounds perfect

**Comment by puffo** [comment]
Notes from an ad-hoc call:

```
// Setup a new express app separately
// Use express middleware to authenticate

// API Specification:
/*
Try tackle the following endpoints in this order:

/seeds/platforms/
/seeds/tracks/
/seeds/contracts/
/seeds/artists/

All with [Create, Update, Delete].

Each will also:
 - validate existence of the right objects, e.g. contracts require a platform
 - explode or try again later with a 422
*/

/*
// Authorization Specification:

Signature:
- body for the signed message
- pk is used to do the signing
_ address is derived from pk

// Example:
signer = web3.eth.accounts.recover(
  request.body,
  request.headers.signature,
);

if(signer == ENV.officialSigner) {
  // Permitted!
} else {
  return 422
}
*/

/*
// General Approach:
- Set up the client, with maybe a test suite to support
- Build client SDK
  - https://docs.ethers.io/v5/api/signer/#Signer-signMessage
  - Maybe take a look at the spinamp sdk, https://github.com/spinamp/spinamp-sdk
  - try to create something like `test-seeds.ts` that allow us to play, auto-sign a message from ENV, and add data do ad-hoc operations
*/
```
